### ISSUE TITLE
Prevent rollbar-go to start a Client by default

### ISSUE THREAD

**Issue by xaviercrochet** [rollbar/rollbar-go#101]
The library is initializing an AsyncClient , by assigning a default value to the std variable in rollbar.go

Even if one would create his own client, a default client is created and assigned to std. 

This is quite problematic,  i.e. when building tests, as a go routine is started by default, preventing to to verify your application is leaking goroutines.

The only workaround at the moment is to call Close() to stop the default Client. 

A way to disable this feature would be nice, i.e. when one disable the default client using SetEnabled(false).

**Comment by cyrusradfar** [comment]
Hi @xaviercrochet we're going to pick this up shortly and find someone to get this done. Appreciate your support in approving the SDK for our community.
