### ISSUE TITLE
Consider tagging submodule "errors"?

### ISSUE THREAD

**Issue by Rick-xuy** [rollbar/rollbar-go#106]
I found that package `github.com/rollbar/rollbar-go/errors` is placed in submodule `github.com/rollbar/rollbar-go/errors` instead of root module. <br>
However, it seems that submodule `github.com/rollbar/rollbar-go/errors` is not tagged. According to [Go Modules wiki](https://github.com/golang/go/wiki/Modules#is-it-possible-to-add-a-module-to-a-multi-module-repository), submodule should be tagged like `relative-path-to-root/vX.X.X`.
At now, when trying to import package `github.com/rollbar/rollbar-go/errors`, downstream would depends on **pseudo-version** of module `github.com/rollbar/rollbar-go/errors`.
```
github.com/rollbar/rollbar-go/errors v0.0.0-20191126182519-4b2c800372e7
```
I think it is not very readable and difficult to upgrade. This is not conductive to version control either.
So, I propose whether it is possible to tag submodule properly. For example, `errors/v0.0.1`, `errors/v1.4.5`etc, so that other project can use tag to import this module in go.mod.

**Comment by zdavis-rollbar** [comment]
added submodule tagging:

go get [github.com/rollbar/rollbar-go/errors@v1.0.0](http://github.com/rollbar/rollbar-go/errors@v1.0.0) now works
