### ISSUE TITLE
go reporting the compile error on the example.

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/rollbar-go#17]
Hi,

I have followed the document instruction to use Rollbar Go notifier. I have observed following issue.

1. With the example that you have mentioned in the documentation. It's generating compile time error.
```
func main() {
  rollbar.SetToken("MY_TOKEN")
  rollbar.SetEnvironment("production")  // defaults to "development"
  rollbar.SetCodeVersion("v2")   // optional Git hash/branch/tag (required for GitHub integration)
  rollbar.SetServerHost("web.1")   // optional override; defaults to hostname
  rollbar.SetServerRoot("github.com/heroku/myproject") // path of project (required for GitHub integration   and non-project stacktrace collapsing)

 result, err := DoSomething()
 if err != nil {
    rollbar.Critical(err)
 }
  rollbar.Info("Message body goes here")
  rollbar.Wait()
}
```
It's generating compile time error. I have made my own example which is working perfectly fine and able to send the log to the rollbar console. The example is.
```
package main
import (
  "github.com/rollbar/rollbar-go"
  "errors"
  "fmt"
  "time"
)
func recoverError() {  
   if r := recover(); r!= nil {
       fmt.Println(r)
       rollbar.Critical(r)
       rollbar.Wait()    
   }
}

func main() {
    defer catchError()
    rollbar.SetToken("MY-TOKEN")
    rollbar.SetEnvironment("production")
    var timer *time.Timer = nil
    timer.Reset(10) // crash
}
```
2. With the Notifier integration. We need to run following command to import rollbar package inside the code.
```
go get github.com/rollbar/rollbar-go
```
I think you have forgotten to add in the documentation. I have tried without `go get` command it was throwing package error.
![rollbar-package-error](https://user-images.githubusercontent.com/32199575/37510779-4b44bf4e-2922-11e8-8645-1e8382bc2180.PNG)

Thanks and regards.

Wahid Ali

**Comment by rokob** [comment]
That is not a compilable example, it is a usage example. `DoSomething` is not defined anywhere and dependency management is outside the scope of using the library. If you want an example that compiles as is (modulo fetching the package) then see https://github.com/rollbar/rollbar-go/blob/master/example/main.go.

**Comment by mostlyjason** [comment]
@rokob don't you think we should choose a usage example that actually compiles? I know I was confused by this. These are first time users looking at our docs and quickstart guide. I would hate for them to be confused and abandon their trial.

**Comment by rivkahstandig3636** [comment]
I agree with @mostlyjason, let's change the example or make it clearer.
