### ISSUE TITLE
Remove global mutable state

### ISSUE THREAD

**Issue by cep21** [rollbar/rollbar-go#18]
Hi,

I understand this is currently just in beta. Are you open to rethinking the API? I forked a similar library to remove package global state. You can read more about package global state at https://dave.cheney.net/2017/06/11/go-without-package-scoped-variables or https://peter.bourgon.org/blog/2017/06/09/theory-of-modern-go.html

I worry the library, currently designed, forces a large amount of global mutable state which could limit usage.

The library also assumes concurrency with `Wait`.  Ideally this could be handed off or be a concern separate from the library.  For example, someone else could have other concurrency ideas or fallback ideas.

I think ideally the client library should be simple and blocking, with the ability to augment that behavior.  Here is the API for my fork.

```
		c := Client{
			Endpoint:    s.URL,
			AccessToken: "abc",
		}
```

Then, the library mirrors rollbar's real API allowing people to send values and even inspect results.

```
			resp, err := c.Message(ctx, Debug, "TestCodeVersion")
			So(err, ShouldBeNil)
			So(resp.Result.UUID, ShouldNotEqual, "")
```

**Comment by rokob** [comment]
This library has a blocking implementation of the sender but it is not the default. It uses global state in the convenience set of functions in rollbar.go but you are free to instantiate a Client directly and use it how you describe. The use of wait is again provided for convenience but is by no means the only way to use this library.
