### ISSUE TITLE
Add log level config option

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-go#27]
Similar to rollbar.js logLevel

**Comment by brianr** [comment]
Closing this as won't do.

Note for readers, rollbar-go can send the message in 2 ways: 

1. Using `Info()`, `Error()`, `Warning()`, `Debug()`, `Critical()` methods directly on the rollbar package - level is defined explicitly.
2. Using `Log(level string, interfaces ...interface{})` method and passing the level as a string.
