### ISSUE TITLE
Recommended go client

### ISSUE THREAD

**Issue by ferhatelmas** [rollbar/rollbar-go#3]
It seems this isn't maintained and readme references [stvp/rollbar](https://github.com/stvp/rollbar) in usage example. However, no mention of status of this repo and relation of above repo. 

Could you briefly explain status/expectations and if needed, please direct people to above client with a small note in readme ? Thanks!

**Comment by rokob** [comment]
The readme references just need to be updated. This library has gone through a few different owners due to forks that have then not been merged. This library is the recommended library going forward as it is a fork of heroku’s fork of the stvp library.
