### ISSUE TITLE
Only collect person.id by default for person tracking

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-go#30]
Allow the ability to send person.email and person.username, but by default we should only collect person.id going forward.

@rokob This is a top priority.

**Comment by rokob** [comment]
The way the person object works here is via the call to `SetPerson(id, email, username string)` Therefore, you have to explicitly set the username and email if you so desire. We are not trying to magically grab it from anywhere, so the configuration option to turn it on/off is essentially whether you set it or not. Therefore I think this can be closed as working already.
