### ISSUE TITLE
Also capture stack on non-error panics

### ISSUE THREAD

**Issue by courajs** [rollbar/rollbar-go#35]
When `Wrap()` catches a panic that is not an instance of err, it doesn't include the stack trace in the report. [`runtime.Stack()`][stack] can be used to capture the stack trace for the current panic, see https://groups.google.com/forum/#!topic/golang-nuts/MB8GyW5j2UY

[stack]: https://golang.org/pkg/runtime/debug/#Stack

**Comment by rivkahstandig3636** [comment]
Thanks for letting us know!
