### ISSUE TITLE
Are two async transports go routines running if you create your own client?

### ISSUE THREAD

**Issue by ldelossa** [rollbar/rollbar-go#43]
Hey guys,

Looking at the code in this library and I notice that in `rollbar.go` you create a global variable `std` which calls `NewAsync()`. This method eventually creates a AsyncTransport which launches a Go routine blocking on the transport's channel.

If I was to create my own client struct, I would also import the root rollbar package and the standard logger would continue to run in the backend. 

Is this by design to always provide a default logger ?

**Comment by rivkahstandig3636** [comment]
Hi @ldelossa, Unfortunately our primary maintainer of this SDK is out for a bit and we haven't been able to get an answer to your question. I'm sorry for the delay!

**Comment by rivkahstandig3636** [comment]
It looks like this is something we should address and change the design of once our SDK engineer is back. Unfortunately that will be a few weeks. I've added this to our next milestone. I'm sorry again for the long delay.

**Comment by jessewgibbs** [comment]
I'm gonna close this since there's been no response.
