### ISSUE TITLE
Add support for `x-forwarded-for` header

### ISSUE THREAD

**Issue by Naatan** [rollbar/rollbar-go#49]
Currently there is no way to manually specify an IP address, only to specify a request. The problem this creates is that rollbar does not seem to make any attempt to infer the IP address beyond looking at the remote address. In many large scale deployments the IP address is set via an `x-forwarded-for` header because the remote address is that of a load balancer.

So, please add support for the `x-forwarded-for` header. Or give us the ability to manually set the IP address.

Thanks!

**Comment by jessewgibbs** [comment]
@naatan thanks for the suggestion.  We'll put this into the backlog and get in touch if we have questions or an update.
