### ISSUE TITLE
Option to use deepest stack trace possible

### ISSUE THREAD

**Issue by fgblomqvist** [rollbar/rollbar-go#56]
At the moment, if the cause error does not have a stack trace, rollbar-go builds a stack trace itself. In an application where rollbar-go is used at a very high level, e.g. at the root of the application execution, this self-built stack trace becomes almost useless. Instead, I think it would be very useful if there was an option (or simply the default behavior) that enables rollbar-go to save the deepest stack trace it can find instead of just checking the cause error. This shouldn't be very complicated to implement based on the current code base, and I think the sample use case I've outlined below is a very common one.

**Sample use case:**
In your application, you do all the rollbar reporting at the root, as in, you report all errors that surface up to main(). Furthermore, you also capture a stack trace every time you create/wrap an error (e.g. if pkg/errors is used, this happens). Whenever a 3rd-party error (for example, one that lacks a stack trace) surfaces into your application, it will get a stack trace attached to it, showing where this error "entered" your code. With the above addition, it will now be much clearer to see in Rollbar where in your code this error surfaced, and combined with the error message, help you resolve it as quickly as possible. It will also make the automatic Rollbar fingerprinting much more accurate since it will be able to distinguish errors in different parts of the code with the same error message/class etc.

**Comment by rokob** [comment]
I am confused why the `Stack` method on the CauseStacker interface does not solve this? If you are building a stack trace every time you create/wrap an error then we should be using that stack rather than building one. Is it because we build a trace_chain based on the cause and the cause might not have a stack so we end up with multiple stack traces in the payload? Does the UI show the stacktrace only for the cause?

**Comment by fgblomqvist** [comment]
You're correct. Just looked over my code and I was in fact incorrectly giving rollbar-go the cause error instead of the parent (meaning that all the higher up stacks got thrown away before rollbar-go could even touch them). My bad, I should have looked it over before I submitted this.
