### ISSUE TITLE
Any example for adding rollbar to serverless ? 

### ISSUE THREAD

**Issue by Hareramrai** [rollbar/rollbar-go#58]
I am using below serverless framework with golang.

https://serverless.com

https://github.com/yunspace/serverless-golang

Does any know how to add global error handling with rollbar & this framework?

**Comment by waltjones** [comment]
Hi @Hareramrai There isn't currently a middleware for serverless. You can add to your handler, whether using serverless or any Lambda handler, by importing and setting your token.
```
import "github.com/rollbar/rollbar-go"
rollbar.SetToken("YOUR_TOKEN")
```
And Rollbar is ready to use.
