### ISSUE TITLE
set a new transport 

### ISSUE THREAD

**Issue by letaniaferreira** [rollbar/rollbar-go#62]
The way to set a new transport would be something like:
rollbar.std.Transport = NewTransport

However, this fails because std is not exported and therefore not accessible to the user.  (This could also be done with an exported setter function, but that doesn't exist either, so either way a necessary interface appears missing.)

This looks like an oversight, and probably no one has ever set a new transport, and this is just now being discovered.

Until there is a fix, they should try to use WrapAndWait or a similar idea. If they run into issues with this, they can send an example and maybe we can hep work through it.

https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/23277315799

**Comment by waltjones** [comment]
I helped with the original investigation of this. Looking now with fresh eyes.

This is probably handled best by creating a custom `Client`, and then the transport is settable. I looked at updating the docs, but this section seems to already describe it pretty well. 
https://github.com/rollbar/rollbar-go/blob/v1.1.0/doc.go#L32-L34

Any feedback on the doc or the interface is welcome.
