### ISSUE TITLE
client/transport.Close() does not support context

### ISSUE THREAD

**Issue by swojtasiak** [rollbar/rollbar-go#80]
The close operation for client (and transport as well) should take context argument to make it possible to interrupt the method if it takes to long to send/close everything.

**Comment by ijsnow** [comment]
The API is the standard library's [`Closer` interface.](https://pkg.go.dev/io#Closer) Are you hoping for a separate interface entirely?

**Comment by pawelsz-rb** [comment]
@swojtasiak , can you check this PR https://github.com/rollbar/rollbar-go/pull/99 and let me know if this is what you want? Also I can add some public context setters. thx!

**Comment by nieblara** [comment]
@swojtasiak Does that PR meet the expectations you had in mind?
