### ISSUE TITLE
Will you release this pkg anymore?

### ISSUE THREAD

**Issue by shirakiya** [rollbar/rollbar-go#81]
I want to take this commit https://github.com/rollbar/rollbar-go/pull/69 into my project. This package has stopped with the release of v1.2.0, but its commit is not included in v1.2.0.

Will you release this package anymore? Or please let me know if there is another method to use it.

Best regards.

**Comment by waltjones** [comment]
Sorry for the delay. A new release including everything currently on master should be tagged by tomorrow.

**Comment by waltjones** [comment]
https://github.com/rollbar/rollbar-go/releases/tag/v1.3.0

**Comment by shirakiya** [comment]
Thanks for your work! It's very helpful!
I think you can close this issue, but I don't as there may be some workflow.
