### ISSUE TITLE
Async transpot can panic

### ISSUE THREAD

**Issue by Naatan** [rollbar/rollbar-go#90]
Due to a recursion issue we've been hitting rollbar limits. To address these issues we temporarily disabling bursting on Rollbar. Unfortunately this seems to result in a panic in the rollbar-go async client.

![CleanShot 2022-01-07 at 13 38 35](https://user-images.githubusercontent.com/278649/148610804-0782240e-eae9-4805-97b0-b510d11f810a.png)

The fact may be that we are sending rollbar messages even though the connection has been closed. Obviously that's an issue on our end, and we're looking into that.

But the fact that a library meant for logging errors can itself cause these kinds of panics is worrying. Worst yet; because the panic happens in a subroutine we cannot do anything in our application to gracefully handle such issues in the future.

It would be nice if the rollbar-go library had a panic recovery in its subroutine. Maybe have it still default to a panic but give developers a way to override that default behavior.

**Comment by Naatan** [comment]
Upon further investigation, the issue appears to be that the API is returning an error, but the retry mechanism will cause it to try again. This retry mechanism does not account for the channel being closed.

**Comment by pawelsz-rb** [comment]
@Naatan , we are addressing that in this PR: https://github.com/rollbar/rollbar-go/pull/100
