### ISSUE TITLE
Breaking API change with release of v1.4.3

### ISSUE THREAD

**Issue by bjohnso5** [rollbar/rollbar-go#97]
Not exporting the type returned by the rollbar `New*` factory functions is a pretty significant breaking change, and prevents developers from embedding the client in a struct or casting it out of a context.

I think this change should be reconsidered.

**Comment by juanantoniocid** [comment]
The `New()` function defined in `client.go` is intended to return the default implementation of a Client, but then you return a value whose type is not exported. It has broken our code (it is supposed a patch version change shouldn't break anything).

What is the purpose of `New()` if it is not used internally and the returned value is not exported?

**Comment by pawelsz-rb** [comment]
I think the idea was to use rollbar package directly (from rollbar.go) without instantiating the Client directly. So to me, exported methods from rollbar.go and exported methods from client.go don't make sense. But if a lot of people are using Client directly and skip the stuff from rollbar.go then I am willing to revert the change and rerelease.

**Comment by ijsnow** [comment]
Sorry for the breaking change. I agree the intended use wasn’t client directly. Our original mistake was to leak that as public in the first place but now it would be useful to learn what the benefits of keeping it in a struct or context. 
Could you elaborate on your usage of client as opposed to a globally configured instance in rollbar.go?

**Comment by pawelsz-rb** [comment]
I have reverted the change for private client and rereleased v1.4.3. Sorry about that breaking change, I guess my assumption was incorrect and it's too late to change anything now.

**Comment by pawelsz-rb** [comment]
closing for now, but please let me know if there are any problems. thank you

**Comment by juanantoniocid** [comment]
> I have reverted the change for private client and rereleased v1.4.3. Sorry about that breaking change, I guess my assumption was incorrect and it's too late to change anything now.

No worries @pawelsz-rb and thanks a lot for handling it so fast!

**Comment by bjohnso5** [comment]
@pawelsz-rb I think we might need a new 1.4.4 release to actually propagate this change, when I clear my go mod cache and re-download 1.4.3, I still get the version with the unexported `rollbar.client` struct

**Comment by pete-woods** [comment]
That's correct, it's basically impossible to re-release a Go module version (Google's module cache prevents it)
